import accordion from './includes/accordion.js';
import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import scrollToId from './includes/scrollToId.js';
import modal from './includes/modal.js';
import closeAlert from './includes/closeAlert.js';
import latestSlider from './includes/latestSlider.js';
import loadMore from './includes/loadMore.js';
import productsSlider from './includes/productsSlider.js';
import photoSwipe from './includes/photoSwipe.js';
import select from './includes/select.js';
import contactFormValidation from './includes/contactFormValidation.js';
import signUpFormValidation from './includes/signUpFormValidation.js';
import forgotFormValidation from './includes/forgotFormValidation.js';
import setupFormValidation from './includes/setupFormValidation.js';
import showNumber from './includes/showNumber.js';
import gallery from './includes/gallery.js';
import range from './includes/range.js';
import filterLoadMore from './includes/filterLoadMore.js';
import filter from './includes/filter.js';
import searchFormValidation from './includes/searchFormValidation.js';
import searchModalFormValidation from './includes/searchModalFormValidation.js';
import wishToggle from './includes/wishToggle.js';
import upButtonVisible from './includes/upButtonVisible.js';
import '../sass/main.sass';


accordion();
fixHeight();
mobileNav();
scrollToId();
modal();
closeAlert();
latestSlider();
loadMore();
productsSlider();
photoSwipe();
select();
contactFormValidation();
signUpFormValidation();
forgotFormValidation();
setupFormValidation();
showNumber();
gallery();
range();
filterLoadMore();
filter();
searchFormValidation();
searchModalFormValidation();
wishToggle();
upButtonVisible();